### ISSUE TITLE
sp stop working

### ISSUE THREAD

**Issue by zablah** [Garee/sp#3]
sp module stop working, maybe the startpage api was changed.

**Comment by Garee** [comment]
Thanks for reporting this @zablah.

The structure of the search response has changed on startpage's end - I need to update the code to parse it correctly. I'll fix this.

**Comment by Garee** [comment]
I've published a new version 1.0.2 with a fix. Can you please update and let me know if it fixes the issue for you?

`$ pip install spcli --upgrade `

**Comment by Garee** [comment]
I'll re-open this issue if it's still a problem for you.
